### ISSUE TITLE
Build problem calibrate_kinect_ir.cpp

### ISSUE THREAD

**Issue by laanwj** [rgbdemo/rgbdemo#21]
With the latest master (d51054b) I get the following build errors:

```
.../rgbdemo/calibration/calibrate_kinect_ir.cpp:116:39: error: ‘kinect_shift_ir_to_depth’ was not declared in this scope
.../rgbdemo/calibration/calibrate_kinect_ir.cpp:127:67: error: ‘showCheckerboardCorners’ was not declared in this scope
```

This seems to have been introduced with commit f6ca4ed, that emptied `calibration_common.h`  and `calibration_common.cpp`.

Edit: none of the calibration sources seem to build at the moment

**Comment by laanwj** [comment]
Seems I made a mistake with ntk versions, this is fixed now, closing.
